name: checkout and ls
on: [push]
jobs: 
  checkout-and-ls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd pose-bootcamp-code-quality-workshop
      - run: cmake -S . -B build
      - run: cmake --build build
      - run: ./build/address_book_tests